### ISSUE TITLE
faced an issue---Pixel 5(Android 11)

### ISSUE THREAD

**Issue by langzhou11** [P1sec/QCSuper#127]
I tried testing a Pixel 5(Android 11) on Ubuntu 22.04 by running:
sudo WIRESHARK_CONFIG_DIR=/home/$USER/.config/wireshark ./qcsuper.py --usb-modem 05c6:901d --wireshark-live
but encountered the following errors:
[17:21:21 | INFO @ usb_modem_pyusb.py:81 ] Connection from the USB link closed
[17:21:21 | ERROR @ usb_modem_pyusb.py:58 ] [!] Can't write to the USB device. Maybe you need root/administrator privileges, or the device was unplugged?

Traceback (most recent call last):
  File "/home/langz/qcsuper/src/inputs/usb_modem_pyusb.py", line 56, in send_request
    self.dev_intf.write_endpoint.write(raw_payload)
  File "/usr/local/lib/python3.10/dist-packages/usb/core.py", line 408, in write
    return self.device.write(self, data, timeout)
  File "/usr/local/lib/python3.10/dist-packages/usb/core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  ...
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)

[17:21:23 | ERROR @ _base_input.py:171 ] Traceback (most recent call last):
  File "/home/langz/qcsuper/src/inputs/_base_input.py", line 167, in _read_thread
    self.read_loop()
  File "/home/langz/qcsuper/src/inputs/usb_modem_pyusb.py", line 95, in read_loop
    read_buffer += data_read
UnboundLocalError: local variable 'data_read' referenced before assignment
Has anyone else faced this issue or knows the solution?

**Comment by Timez-zx** [comment]
I also face the same problem with Samsung Galaxy Ultra 23. No packets can be captured.
