### ISSUE TITLE
Oneplus 3 adb_bridge not working

### ISSUE THREAD

**Issue by madushan1000** [P1sec/QCSuper#2]
Hi,
I can't get this to work on one plus 3 android 8.1 oreo. Looks like it has some issues with the adb_bridge arm executable. I'm getting `ioctl: Invalid argument` when I try to run the binary on the phone. I'm including the relevant section of the strace bellow and I'm happy to help you to with figuring this issue out.

```
openat(AT_FDCWD, "/dev/diag", O_RDWR|O_LARGEFILE) = 3
ioctl(3, _IOC(0, 0, 0x20, 0), 0xaaab5088) = 1
ioctl(3, _IOC(0, 0, 0x7, 0), 0x2)       = -1 EFAULT (Bad address)
ioctl(3, _IOC(0, 0, 0x7, 0), 0xaaaab3a4) = -1 EINVAL (Invalid argument)
writev(2, [{iov_base="ioctl", iov_len=5}, {iov_base=": ", iov_len=2}, {iov_base="Invalid argument", iov_len=16}, {iov_base="\n", iov_len=1}], 4ioctl: Invalid argument
) = 24
mprotect(0xf75f6000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0xf75f6000, 4096, PROT_READ)   = 0
mprotect(0xf75f6000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0xf75f6000, 4096, PROT_READ)   = 0
munmap(0xf75f6000, 4096)                = 0
exit_group(1)                           = ?
```

**Comment by p1-mmr** [comment]
Hello,

Thank you for your feedback and ioctl log! I have updated the concerned source code in 02c2a543c1cfdf306f61f2e5ef6e0f415ac001bb, and recompiled the binary. Can you tell me whether you obtain different results?

Regards,

**Comment by madushan1000** [comment]
Hi, 

Looks like that issue is fixed, but now, when I use `adb shell` and run the `adb_bridge` as root on the phone. It prints `Connection to Diag established`. 

But, If I run `adb shell su -c /data/local/tmp/adb_bridge` (like the python script does), it doesn't print above message. Since the python script expects this output, python script just get stuck when I run `./qcsuper.py --adb --wireshark-live`

I tried commenting out the for loop at https://github.com/P1sec/QCSuper/blob/master/inputs/adb.py#L141, but then I get a crash 

```
Traceback (most recent call last):
  File "/Users/madushan/Dev/my/QCSuper/inputs/_base_input.py", line 156, in _read_thread
    self.read_loop()
  File "/Users/madushan/Dev/my/QCSuper/inputs/adb.py", line 249, in read_loop
    socket_read = self.socket.recv(1024 * 1024 * 10)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by madushan1000** [comment]
Just figured out that if I run the adb_bridge as root separately, and then run the script. It works properly, I can see the packets showing up in wireshark.

**Comment by p1-mmr** [comment]
Thank you for your feedback; when you were talking about "running the adb_bridge as root separately", is this about running another command than `adb shell su -c /data/local/tmp/adb_bridge`? e.g., using `adb root`, spawning an `adb shell` then running the `su -c` command, using the `sudo` command, or another mean?

If no, does it differ from just running `adb shell su -c /data/local/tmp/adb_bridge` as mentioned above?

Thank you!

**Comment by madushan1000** [comment]
Yeah, running `adb shell su -c /data/local/tmp/adb_bridge`, and then running `./qcsuper.py --adb --wireshark-live` works. Even though the first command doesn't output anything to stdout.

**Comment by p1-mmr** [comment]
Ok. Here are a few things I would suggest for further troubleshooting:
* May it be confirmed whether replacing `adb shell` with `adb exec-out` (i.e, editing the [`inputs/adb.py`](https://github.com/P1sec/QCSuper/blob/master/inputs/adb.py) file of the source code) and replacing `'shell'` with `'exec-out'` outputs something? I have read that this more recent adb command may ensure that buffering is disabled. However it may not work on older devices.
* Can you provide the version for your local and remote adb instances, by running: `adb version` and `adb shell su -c "adbd --version"`
* Can you confirm whether you can run other commands through `adb shell su -c` and obtain output, for example: `adb shell sh -c id`
* Can you confirm whether you are using a Linux system?

Regards,

**Comment by pierlon** [comment]
I'm having the same problem as @madushan1000. Replacing `shell` with `exec-out` does fix the issue.

Also something to note, if I disconnect the device and reconnect it I get the error `ioctl: Invalid argument`. Setting up a signal handler to close `diag_fd` probably should fix that.

**Comment by cewatkins** [comment]
I needed to add sleep 5, cause file not quite there it thinks.
